version: "1"

services: 
  breeds:
    build: ./breeds-service
  dogs:
    build: ./dogs-service
  awards:
    build: ./awards-service

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - breeds
      - dogs
      - awards